// ─────────────────────────────────────────────
//  Supabase client — preparado para integração
//  Descomente quando adicionar Supabase ao projeto:
//    npm install @supabase/supabase-js
//  e adicione as vars no .env.local
// ─────────────────────────────────────────────

/*
import { createClient } from '@supabase/supabase-js'

const supabaseUrl  = process.env.NEXT_PUBLIC_SUPABASE_URL!
const supabaseKey  = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!

if (!supabaseUrl || !supabaseKey) {
  throw new Error('Missing Supabase environment variables')
}

export const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
})

// ── Helper types (generated by Supabase CLI) ──
// Run: npx supabase gen types typescript --project-id <your-id> > src/types/supabase.ts

export type { Database } from '@/types/supabase'
*/

// Placeholder — will be replaced with real Supabase client
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase = null as unknown as any
